[package]
name = "server"
version = "0.1.0"
description = "An express-like server for Motoko"
repository = "https://github.com/krpeacock/server"

[dependencies]
certified-cache = "0.2.0"
json = "https://github.com/aviate-labs/json.mo#master"
array = "https://github.com/aviate-labs/array.mo#master"
encoding = "https://github.com/aviate-labs/encoding.mo#master"
motoko-sha = "https://github.com/enzoh/motoko-sha#master"
serde = "0.2.0"
test = "1.0.1"
base = "0.8.7"