[package]
name = "server"
version = "0.3.1"
description = "An express-like server for Motoko"
repository = "https://github.com/krpeacock/server"
keywords = ["motoko", "server", "express", "http", "certified", "cache", "assets"]
license = "Apache-2.0"

[dependencies]
certified-cache = "0.2.1"
json = "https://github.com/aviate-labs/json.mo#main@afd30ed75095cb339c1ec187d61030bbd2e59ae6"
array = "https://github.com/aviate-labs/array.mo#main@8e4282825d3b401407954917cd94d1548ee21256"
encoding = "https://github.com/aviate-labs/encoding.mo#main@2711d18727e954b11afc0d37945608512b5fbce2"
motoko-sha = "https://github.com/enzoh/motoko-sha#master@9e2468f51ef060ae04fde8d573183191bda30189"
serde = "2.2.0"
test = "1.2.0"
base = "0.10.4"
assets = "0.2.1"
"http-parser.mo" = "https://github.com/NatLabs/http-parser.mo#v0.1.2@27cba8ed0d39387e0fb660f65909ffe2a7d54413"
