[package]
name = "http_hello"
version = "0.1.0"
description = ""
repository = ""

[dependencies]
server = "0.1.0"
certified-cache = "0.2.0"
assets = "0.2.0"
http-parser = "0.1.0"
"http-parser.mo" = "https://github.com/NatLabs/http-parser.mo#v0.1.2"
